### ISSUE TITLE
Left align the navbar for categories of products in mobile view

### ISSUE THREAD

**Issue by algomaster99** [IMGIITRoorkee/omniport-frontend-buy-and-sell#8]
![Screenshot_20200220-114949__01](https://user-images.githubusercontent.com/35191225/74906617-8dc82680-53d7-11ea-9b65-892166691ada.jpg)

**Comment by gagansh7171** [comment]
I would like to work on this issue

**Comment by algomaster99** [comment]
@gagansh7171 all yours 💯

**Comment by gagansh7171** [comment]
@algomaster99 there is a popup in the mobile and tab view of the navbar. Can you help me realize its purpose?

![Screenshot from 2020-09-25 21-19-04](https://user-images.githubusercontent.com/52528493/94288298-e1ee4700-ff74-11ea-82c8-87606fc4d4c0.png)
